import { Router } from "express";
import { authenticate, requireRole, tenantContext, validate } from "../../common/middleware/index.js";
import { asyncHandler } from "../../common/middleware/asyncHandler.js";
import { sendSuccess } from "../../common/utils/response.js";
import { createGrantSchema, grantIdSchema } from "./support.schema.js";
import { supportService } from "./support.service.js";
export const supportRouter = Router();
supportRouter.use(authenticate, tenantContext);
supportRouter.get("/diagnostics", requireRole("SUPPORT"), asyncHandler(async (req,res)=>{const c=req.tenantContext!;sendSuccess(res,200,await supportService.diagnostics(req.header("x-support-grant-id"),c.tenantId,c.membershipId,c.userId),req.requestId);}));
supportRouter.get("/access-grants", requireRole("OWNER"), asyncHandler(async(req,res)=>{sendSuccess(res,200,{grants:await supportService.list(req.tenantContext!.tenantId)},req.requestId);}));
supportRouter.post("/access-grants", requireRole("OWNER"), validate(createGrantSchema), asyncHandler(async(req,res)=>{const c=req.tenantContext!;sendSuccess(res,201,await supportService.create(req.body,c.tenantId,c.userId),req.requestId);}));
supportRouter.delete("/access-grants/:grantId", requireRole("OWNER"), validate(grantIdSchema,"params"), asyncHandler(async(req,res)=>{const c=req.tenantContext!;sendSuccess(res,200,await supportService.revoke(String(req.params.grantId),c.tenantId,c.userId),req.requestId);}));
