import type { MembershipRole } from "@prisma/client";

/**
 * The invitation letter.
 *
 * Written here rather than generated by a model. A model was considered and
 * rejected for this: an invitation is a short, formulaic, outbound message to
 * someone who does not yet trust the sender, and it is the first thing they
 * ever see from the workspace. It should read identically every time, be
 * reviewable before anyone is invited, and never depend on a third-party API
 * being up or a key being present. So the wording is deliberate and the only
 * variable parts are the facts.
 *
 * Returned as parts rather than one string, because the admin edits the body
 * before sending and the mailer lays out the greeting, body and footer
 * separately.
 */

export interface InvitationLetterInput {
  firstName?: string | null;
  lastName?: string | null;
  /** Used for the greeting only when no name was given. */
  email: string;
  role: MembershipRole;
  workspaceName: string;
  inviterName: string;
  expiresInHours: number;
}

export interface InvitationLetter {
  subject: string;
  /** "Dear Priya Sharma," — the wireframe's first line. */
  greeting: string;
  /** The body, one string per paragraph. This is what the admin may edit. */
  paragraphs: string[];
  closing: string;
}

/**
 * What each role will actually be able to do, in the invitee's terms.
 *
 * Worth stating in the letter: someone deciding whether to accept should know
 * what they are being given, and an Owner invitation is a materially different
 * proposition from a Member one.
 */
const ROLE_SUMMARY: Record<MembershipRole, string> = {
  OWNER:
    "As an owner you will have full control of the workspace, including its people, billing and data.",
  ADMIN:
    "As an administrator you will be able to manage people, mailboxes, domains and policies for the workspace.",
  MEMBER:
    "As a member you will have your own mailbox, along with the shared conversations and commitments assigned to you.",
  SUPPORT:
    "As a support contact you will have read-only access to help the workspace, without the ability to change its settings.",
};

/** Article agreement, so the sentence reads correctly for every role. */
const ROLE_NOUN: Record<MembershipRole, string> = {
  OWNER: "an owner",
  ADMIN: "an administrator",
  MEMBER: "a member",
  SUPPORT: "a support contact",
};

/** "Priya Sharma", "Priya", or null when neither name was given. */
export function fullName(
  firstName?: string | null,
  lastName?: string | null
): string | null {
  const parts = [firstName, lastName]
    .map((part) => part?.trim())
    .filter((part): part is string => Boolean(part));
  return parts.length > 0 ? parts.join(" ") : null;
}

/**
 * How long the invitation lasts, in words rather than a raw hour count.
 *
 * "72 hours" is accurate but makes the reader do arithmetic; "3 days" is what
 * they need in order to decide whether to act now.
 */
function describeExpiry(hours: number): string {
  if (hours < 1) return "shortly";
  if (hours < 24) return `${hours} ${hours === 1 ? "hour" : "hours"}`;
  const days = Math.round(hours / 24);
  return `${days} ${days === 1 ? "day" : "days"}`;
}

export function draftInvitationLetter(
  input: InvitationLetterInput
): InvitationLetter {
  const name = fullName(input.firstName, input.lastName);
  const expiry = describeExpiry(input.expiresInHours);

  return {
    subject: `You're invited to join ${input.workspaceName} on Zoiko Mail`,

    // Named when we know the name, and never a placeholder when we do not:
    // "Dear there," reads worse than a plain hello.
    greeting: name ? `Dear ${name},` : "Hello,",

    paragraphs: [
      `${input.inviterName} has invited you to join ${input.workspaceName} on Zoiko Mail as ${ROLE_NOUN[input.role]}.`,

      ROLE_SUMMARY[input.role],

      `To accept, use the button below and finish setting up your account. This invitation is valid for the next ${expiry}.`,

      // Every unexpected-invitation email needs this line: it tells someone
      // who did not ask for it that doing nothing is a safe choice.
      `If you were not expecting this invitation, you can safely ignore this message — no account is created for you until you accept.`,
    ],

    closing: `Sent by ${input.inviterName} on behalf of ${input.workspaceName}.`,
  };
}
