import { Router } from "express";
import { authenticate, requireRole, tenantContext, validate } from "../../common/middleware/index.js";
import { asyncHandler } from "../../common/middleware/asyncHandler.js";
import { sendSuccess } from "../../common/utils/response.js";
import { addDomainSchema, domainIdSchema } from "./domain.schema.js";
import { domainService } from "./domain.service.js";
export const domainRouter = Router();
domainRouter.use(authenticate, tenantContext, requireRole("OWNER", "ADMIN"));
domainRouter.get("/", asyncHandler(async (req, res) => { sendSuccess(res, 200, { domains: await domainService.list(req.tenantContext!.tenantId) }, req.requestId); }));
domainRouter.post("/", validate(addDomainSchema), asyncHandler(async (req, res) => { sendSuccess(res, 201, await domainService.add(req.body.domainName, req.tenantContext!.tenantId, req.tenantContext!.userId), req.requestId); }));
domainRouter.post("/:domainId/diagnostics", validate(domainIdSchema, "params"), asyncHandler(async (req, res) => { sendSuccess(res, 200, await domainService.diagnostics(String(req.params.domainId), req.tenantContext!.tenantId, req.tenantContext!.userId), req.requestId); }));
domainRouter.get("/:domainId/checks", validate(domainIdSchema, "params"), asyncHandler(async (req, res) => { sendSuccess(res, 200, { checks: await domainService.listChecks(String(req.params.domainId), req.tenantContext!.tenantId) }, req.requestId); }));
domainRouter.post("/:domainId/activate", validate(domainIdSchema, "params"), asyncHandler(async (req, res) => { sendSuccess(res, 200, await domainService.activate(String(req.params.domainId), req.tenantContext!.tenantId, req.tenantContext!.userId), req.requestId); }));
domainRouter.delete("/:domainId", validate(domainIdSchema, "params"), asyncHandler(async (req, res) => { sendSuccess(res, 200, await domainService.remove(String(req.params.domainId), req.tenantContext!.tenantId, req.tenantContext!.userId), req.requestId); }));
